apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restfuljobs.restfulcontroller.github.com.sunxiaoning
  # for more information on the below annotation, please see
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  group: restfulcontroller.github.com.sunxiaoning
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                method:
                  type: string
                  enum:
                    - GET
                    - POST
                    - PUT
                    - Delete
                headers:
                  type: array
                  items:
                    type: string
                maxRetry:
                  type: integer
                  default: 0
                suspend:
                  type: bool
                  default: false
            status:
              type: object
              properties:
                logs:
                  type: string
                status:
                  type: string
                output:
                  type: object
                  properties:
                    code:
                      type: integer
                    msg:
                      type: string
                    data:
                      type: string

  names:
    kind: RestfulJob
    plural: restfuljobs
  scope: Namespaced
